// src/app.jsx
// Main app - routing + state
const { useState: useS, useEffect } = React;

// Nulstil demo i Tweaks: samme handling som knappen nederst i sidebjælken
// (confirmResetDemo i shell.jsx): bekræft, og kald så CW.resetDemo().
function ResetDemoButton() {
  return (
    <button
      className="btn btn-sm"
      style={{ width: '100%', justifyContent: 'center' }}
      onClick={() => window.confirmResetDemo()}
      title={t('Rydder alt demoen har gemt (sagens fase, uploads, memo) og genindlæser')}
    >
      <I.Refresh size={12}/> {t('Nulstil demo')}
    </button>
  );
}

// Sidens titel pr. rute, fx "Nordhavn Composite A/S · Credit memo · Crediwire"
const WS_TAB_TITLES = { overview: 'Overblik', financials: 'Virksomheden', documents: 'Dokumenter', memo: 'Credit memo', indstil: 'Indstilling' };
function routeTitle(route) {
  const parts = [];
  if (route.startsWith('workspace:')) {
    const [, id, tab] = route.split(':');
    const c = DATA.caseById ? DATA.caseById(id) : null;
    parts.push(c ? c.name : t('Sag'));
    parts.push(t(WS_TAB_TITLES[tab || 'overview'] || 'Sagen'));
  } else {
    const map = { cases: 'Mine opgaver', requests: 'Dataanmodninger', analyse: 'Porteføljeanalyse', portal: 'Kundeportal', mapping: 'Kontomapping' };
    parts.push(t(map[route] || 'Mine opgaver'));
  }
  parts.push('Crediwire');
  return parts.join(' · ');
}

// Den gemte rute skal pege på en skærm, der findes. En ældre rute (fx den
// fjernede "settings") eller en sag, som "Nulstil demo" har slettet, fører
// til Mine opgaver i stedet for en tom side.
const APP_ROUTES = ['cases', 'requests', 'analyse', 'portal', 'mapping'];
function validRoute(r) {
  if (r && r.startsWith('workspace:')) {
    const id = r.split(':')[1];
    return DATA.caseById && DATA.caseById(id) ? r : 'cases';
  }
  return APP_ROUTES.indexOf(r) >= 0 ? r : 'cases';
}

// Under 1000 px (fx 200 % zoom) ruller sagshovedet og fanerne med indholdet,
// så memoet får højden. Sagen spørger her og flytter så sit rullefelt op, så
// det omfatter hovedet (se .ws-body og .ws-scroller i styles.css).
const SHELL_NARROW_MQ = '(max-width: 999px)';
function cwUseShellNarrow() {
  const [narrow, setNarrow] = useS(() => window.matchMedia(SHELL_NARROW_MQ).matches);
  useEffect(() => {
    const mq = window.matchMedia(SHELL_NARROW_MQ);
    const on = () => setNarrow(mq.matches);
    mq.addEventListener ? mq.addEventListener('change', on) : mq.addListener(on);
    return () => { mq.removeEventListener ? mq.removeEventListener('change', on) : mq.removeListener(on); };
  }, []);
  return narrow;
}
window.cwUseShellNarrow = cwUseShellNarrow;

function App() {
  const [route, setRoute] = useS(() => {
    const saved = localStorage.getItem("cw_route");
    const r = validRoute(saved);
    if (saved && r !== saved) { try { localStorage.setItem("cw_route", r); } catch (e) {} }
    return r;
  });
  const [newCaseOpen, setNewCaseOpen] = useS(false);

  // Tweak defaults (persisted via host)
  const DEFAULTS = /*EDITMODE-BEGIN*/{
    "accent": "ink",
    "density": "calm",
    "sidebar": "full"
  }/*EDITMODE-END*/;

  const [tweaks, setTweak] = window.useTweaks(DEFAULTS);

  // Apply tweaks to CSS
  useEffect(() => {
    const accent = tweaks.accent;
    const r = document.documentElement.style;
    const palettes = {
      ink:   { primary: '#0d0f12', hover: '#2a2d32', ink: '#0d0f12' },
      navy:  { primary: '#1e3a5f', hover: '#2a4c79', ink: '#1a2e4a' },
      petrol:{ primary: '#0f5c63', hover: '#177079', ink: '#13434a' },
      forest:{ primary: '#1f4d3a', hover: '#296048', ink: '#1a3d2f' },
    };
    const p = palettes[accent] || palettes.ink;
    r.setProperty('--c-accent', p.primary);
    r.setProperty('--c-accent-hover', p.hover);
    r.setProperty('--c-ink', p.ink);
  }, [tweaks.accent]);

  // Smalle skærme (under 1000 px, fx 200 % zoom): sidebjælken er foldet ind
  // og åbnes som panel fra menuknappen. Over 1000 px har tilstanden ingen virkning.
  const [navOpen, setNavOpen] = useS(false);
  const navToggleRef = React.useRef(null);
  const navRef = React.useRef(null);
  const closeNav = (focusToggle) => {
    setNavOpen(false);
    // Menuknappen er skjult, mens panelet er åbent; fokus efter næste tegning
    if (focusToggle && navToggleRef.current) CW.focusSoon(navToggleRef.current);
  };
  React.useEffect(() => {
    if (!navOpen) return;
    // Fokus ind i panelet: det aktive menupunkt, ellers det første
    const panel = navRef.current;
    const first = panel && (panel.querySelector('[aria-current="page"]') || panel.querySelector('button'));
    if (first) CW.focusSoon(first);
    // Panelet er en modal dialog (mørk baggrund): Tab bliver i panelet, Esc lukker
    const onKey = (e) => {
      if (e.key === 'Escape') { e.stopPropagation(); closeNav(true); return; }
      if (e.key !== 'Tab' || !panel) return;
      const f = [...panel.querySelectorAll('button, a[href], input, select, textarea, [tabindex="0"]')]
        .filter(x => !x.disabled && x.getClientRects().length);
      if (!f.length) return;
      const a = document.activeElement;
      if (e.shiftKey && (a === f[0] || !panel.contains(a))) { e.preventDefault(); f[f.length - 1].focus(); }
      else if (!e.shiftKey && (a === f[f.length - 1] || !panel.contains(a))) { e.preventDefault(); f[0].focus(); }
    };
    document.addEventListener('keydown', onKey);
    // Bliver skærmen bred igen, lukkes panelet, så det ikke dukker op næste gang
    const mq = window.matchMedia('(max-width: 999px)');
    const onMq = () => { if (!mq.matches) setNavOpen(false); };
    mq.addEventListener ? mq.addEventListener('change', onMq) : mq.addListener(onMq);
    return () => {
      document.removeEventListener('keydown', onKey);
      mq.removeEventListener ? mq.removeEventListener('change', onMq) : mq.removeListener(onMq);
    };
  }, [navOpen]);
  // Forlader fokus panelet (Tab videre, eller en dialog åbner), lukker det
  const onNavBlur = (e) => {
    if (!navOpen) return;
    const to = e.relatedTarget;
    if (to && (navRef.current.contains(to) || to === navToggleRef.current)) return;
    setNavOpen(false);
  };

  // Ruteskift: gem ruten og fortæl resten af appen det (fx lukker CW.toast sig)
  const go = (r) => {
    localStorage.setItem("cw_route", r);
    setRoute(r);
    setNavOpen(false);
    try { window.dispatchEvent(new CustomEvent('cw-route-changed', { detail: { route: r } })); } catch (e) {}
  };

  // Fokus ved sideskift: flyt fokus til den nye sides h1 (ellers main), så en
  // skærmlæser hører, hvor man er, og Tab fortsætter fra toppen af siden.
  // Ikke ved første indlæsning, og ikke når kun en fane i samme sag skifter:
  // fanerne beholder selv fokus. Forsvinder knappen, der skiftede fane (fx
  // "Åbn memo"), får den aktive fane fokus. En skærm, der selv flytter fokus
  // bagefter (fx klokken eller et dybdelink i memoet), vinder, fordi den kommer senere.
  const prevRouteRef = React.useRef(route);
  React.useEffect(() => {
    const prev = prevRouteRef.current;
    prevRouteRef.current = route;
    if (prev === route) return;
    const caseOf = (r) => r.startsWith('workspace:') ? r.split(':')[1] : null;
    const sameCase = caseOf(prev) !== null && caseOf(prev) === caseOf(route);
    const lost = () => !document.activeElement || document.activeElement === document.body || !document.activeElement.isConnected;
    if (sameCase) {
      const tm = setTimeout(() => {
        if (!lost()) return;
        const tab = document.querySelector('.ws-tab[aria-current="page"]');
        if (tab) CW.focusSoon(tab);
      }, 60);
      return () => clearTimeout(tm);
    }
    let n = 0, tm;
    const tick = () => {
      const h = document.querySelector('#main h1') || document.querySelector('h1');
      if (h) { CW.focusSoon(h); return; }
      if (++n < 10) { tm = setTimeout(tick, 50); return; }
      const m = document.getElementById('main');
      if (m) CW.focusSoon(m);
    };
    tick();
    return () => clearTimeout(tm);
  }, [route]);

  // Sidens titel følger ruten. Layout-effekt, så en skærm selv kan sætte en
  // mere præcis titel i sin egen effekt bagefter (fx kundeportalens trin).
  React.useLayoutEffect(() => { document.title = routeTitle(route); }, [route]);

  // Expose router for self-contained components (e.g. global CaseSearch in Topbar)
  React.useEffect(() => { window.__go = go; }, []);

  // Parse route
  const isWorkspace = route.startsWith("workspace:");
  const workspaceParts = isWorkspace ? route.split(":") : [];
  const workspaceCaseId = workspaceParts.length > 1 ? (parseInt(workspaceParts[1]) || 1) : 1;
  const workspaceTab = isWorkspace ? (workspaceParts[2] || "overview") : null;
  const isPortal = route === "portal";

  // "Spring til indhold": flyt fokus til hovedindholdet uden at røre URL'en
  const skipToMain = (e) => {
    e.preventDefault();
    const m = document.getElementById('main');
    if (m) m.focus();
  };

  return (
    <>
      {isPortal ? (
        <CustomerPortal back={() => go("workspace:1")}/>
      ) : (
        <>
        <a href="#main" className="skip-link" onClick={skipToMain}>{t('Spring til indhold')}</a>
        <div className={"app" + (navOpen ? " nav-open" : "")}>
          {/* Menuknap og panel findes kun under 1000 px; over det er
              knappen skjult, og omslaget om sidebjælken er display: contents */}
          <button type="button" ref={navToggleRef} className="icon-btn nav-toggle"
            aria-label={t('Hovedmenu')} title={t('Hovedmenu')}
            aria-expanded={navOpen} aria-controls="cw-sidebar"
            onClick={() => setNavOpen(o => !o)}>
            <Icon size={16}><path d="M4 6h16M4 12h16M4 18h16"/></Icon>
          </button>
          {navOpen && <div className="nav-scrim" aria-hidden="true" onClick={() => closeNav(false)}/>}
          <div className="app-nav" id="cw-sidebar" ref={navRef} onBlur={onNavBlur}
            role={navOpen ? 'dialog' : undefined} aria-modal={navOpen ? 'true' : undefined} aria-label={navOpen ? t('Hovedmenu') : undefined}
            onClick={(e) => { if (e.target.closest && e.target.closest('button') && !e.target.closest('[role=group], [aria-haspopup], [role=menu]')) setNavOpen(false); }}>
            {navOpen && (
              <button type="button" className="icon-btn nav-close" aria-label={t('Luk menuen')} title={t('Luk menuen')}
                onClick={(e) => { e.stopPropagation(); closeNav(true); }}>
                <I.X size={16}/>
              </button>
            )}
            <Sidebar route={route} go={go} openNewCase={() => setNewCaseOpen(true)}/>
          </div>
          <main className="main" id="main" tabIndex={-1}>
            {route === "cases" && <Portfolio go={go}/>}
            {isWorkspace && <WorkspaceShell tab={workspaceTab} caseId={workspaceCaseId} go={go} openMemo={() => go("workspace:" + workspaceCaseId + ":memo")}/>}
            {route === "analyse" && <PortfolioAnalyse go={go}/>}
            {route === "requests" && <DataRequests go={go}/>}
            {/* Demo: kontomappingen (src/mapper.jsx) */}
            {route === "mapping" && <MapperPage go={go}/>}
          </main>
        </div>
        </>
      )}

      {/* Ny sag: fra knappen og fra andre skærme ('cw-new-case', se NewCaseHost i shell.jsx) */}
      <NewCaseHost open={newCaseOpen} close={() => setNewCaseOpen(false)} go={go}/>


      {/* Tweaks panel */}
      <window.TweaksPanel title={t('Tweaks')} defaultOpen={false}>
        <window.TweakSection label={t('Demo')}>
          <ResetDemoButton/>
          {/* Piloten skriver memoet i Word med Copilot; det indbyggede memo er gemt bag dette flag (case_facts.js) */}
          <window.TweakToggle label={t('Indbygget memo og indstilling')} value={window.CW_MEMO_MODE === 'builtin'}
            onChange={(on) => { try { localStorage.setItem('cw_memo_mode', on ? 'builtin' : 'copilot'); } catch (e) {} location.reload(); }}/>
        </window.TweakSection>
        <window.TweakSection label={t('Accentfarve')}>
          <window.TweakColor label={t('Farve')} value={
              tweaks.accent === 'navy' ? '#1e3a5f' :
              tweaks.accent === 'petrol' ? '#0f5c63' :
              tweaks.accent === 'forest' ? '#1f4d3a' : '#0d0f12'
            }
            options={['#0d0f12', '#1e3a5f', '#0f5c63', '#1f4d3a']}
            onChange={(v) => {
              const map = { '#0d0f12':'ink','#1e3a5f':'navy','#0f5c63':'petrol','#1f4d3a':'forest' };
              setTweak('accent', map[v] || 'ink');
            }}/>
        </window.TweakSection>
        <window.TweakSection label={t('Hop til skærm')}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
            <button className="btn btn-sm" onClick={() => go("cases")}>{t('Mine opgaver')}</button>
            <button className="btn btn-sm" onClick={() => go("requests")}>{t('Dataanmodninger')}</button>
            <button className="btn btn-sm" onClick={() => go("analyse")}>{t('Porteføljeanalyse')}</button>
            <button className="btn btn-sm" onClick={() => setNewCaseOpen(true)}>{t('Ny sag')}</button>
            <button className="btn btn-sm" onClick={() => go("workspace:1")}>{t('Sagens overblik')}</button>
            <button className="btn btn-sm" onClick={() => go("workspace:1:financials")}>{t('Finans')}</button>
            <button className="btn btn-sm" onClick={() => go("workspace:1:documents")}>{t('Dokumenter')}</button>
            <button className="btn btn-sm" onClick={() => go("workspace:1:memo")}>{t('Credit memo')}</button>
            <button className="btn btn-sm" onClick={() => go("portal")}>{t('Kundens portal')}</button>
          </div>
        </window.TweakSection>
      </window.TweaksPanel>
    </>
  );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App/>);

// src/App.vue
<script setup>
// Appens skal: sidebjælke, hovedindhold pr. rute, Ny sag, Tweaks og bekræftelser.
// Ruten er den samme strengmodel som før migrationen (src/composables/useNavigation.js).
import { computed, defineAsyncComponent, watch } from 'vue'
import daDK from 'ant-design-vue/es/locale/da_DK'
import enUS from 'ant-design-vue/es/locale/en_US'
import dayjs from 'dayjs'
import { CloseOutlined } from '@ant-design/icons-vue'
import 'dayjs/locale/da'
import { lang, t } from '@/i18n'
import { CW } from '@/domain/case_state'
import { go, isWorkspace, route, routeTitle, workspaceCaseId, workspaceTab } from '@/composables/useNavigation'
import { useShellNarrow } from '@/composables/useShellNarrow'
import { closeNav, navOpen } from '@/composables/useAppShell'
import { useFocusTrap } from '@/composables/useFocusTrap'
import { useDialogFocus } from '@/composables/useDialogFocus'
import AppSidebar from '@/components/shell/AppSidebar.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import NewCaseHost from '@/components/shell/NewCaseHost.vue'
import TweaksPanel from '@/components/shell/TweaksPanel.vue'
import PortfolioView from '@/views/portfolio/PortfolioView.vue'

// Skærmene indlæses først, når de vises (Mine opgaver er startskærmen og indlæses med det samme).
// Logik, der skal køre ved start, ligger i src/domain og indlæses af src/bootstrap.js.
const WorkspaceView = defineAsyncComponent(() => import('@/views/workspace/WorkspaceView.vue'))
const PortfolioAnalyseView = defineAsyncComponent(() => import('@/views/analyse/PortfolioAnalyseView.vue'))
const DataRequestsView = defineAsyncComponent(() => import('@/views/requests/DataRequestsView.vue'))
const MapperView = defineAsyncComponent(() => import('@/views/mapping/MapperView.vue'))
const PromptWorkshopView = defineAsyncComponent(() => import('@/views/prompts/PromptWorkshopView.vue'))
const CustomerPortalView = defineAsyncComponent(() => import('@/views/portal/CustomerPortalView.vue'))

// ant-design-vue's egne tekster (tom tabel, datovælger, knapper i bekræftelser) på appens sprog
const antdLocale = computed(() => (lang === 'en' ? enUS : daDK))
dayjs.locale(lang === 'en' ? 'en' : 'da')

const narrow = useShellNarrow()

// Dialogerne: fokus på første element (ikke antdv's usynlige vagt), lukkeknappen hedder Luk, og Esc og
// Tab virker, også når det fokuserede element er forsvundet (som CW.useDialog før)
useDialogFocus()
// Bliver skærmen bred igen, lukkes panelet, så det ikke dukker op næste gang
watch(narrow, (n) => { if (!n) closeNav() })

// Sidens titel følger ruten. Skærme kan selv sætte en mere præcis titel bagefter.
watch(route, (r) => { document.title = routeTitle(r) }, { immediate: true })

// Ruteskift lukker navigationspanelet på smalle skærme
watch(route, () => closeNav())

// Fokus ved sideskift: flyt fokus til den nye sides h1 (ellers main), så en
// skærmlæser hører, hvor man er, og Tab fortsætter fra toppen af siden.
// Ikke ved første indlæsning, og ikke når kun en fane i samme sag skifter:
// fanerne beholder selv fokus. Forsvinder knappen, der skiftede fane (fx
// "Åbn memo"), får den aktive fane fokus. En skærm, der selv flytter fokus
// bagefter (fx klokken eller et dybdelink i memoet), vinder, fordi den kommer senere.
// flush 'post': først når den gamle side er fjernet, ellers fandt den dens h1.
watch(route, (r, prev, onCleanup) => {
  if (prev === r) return
  const caseOf = (x) => (x.startsWith('workspace:') ? x.split(':')[1] : null)
  const sameCase = caseOf(prev) !== null && caseOf(prev) === caseOf(r)
  const lost = () => !document.activeElement || document.activeElement === document.body || !document.activeElement.isConnected
  let tm
  onCleanup(() => clearTimeout(tm))
  if (sameCase) {
    tm = setTimeout(() => {
      if (!lost()) return
      const tab = document.querySelector('#ws-tabs [role="tab"][aria-selected="true"]')
      if (tab) CW.focusSoon(tab)
    }, 60)
    return
  }
  let n = 0
  const tick = () => {
    const h = document.querySelector('#main h1') || document.querySelector('h1')
    if (h && h.isConnected) {
      CW.focusSoon(h)
      // Blev overskriften udskiftet, før fokus nåede frem (skærm, der indlæses), prøves igen
      tm = setTimeout(() => { if (lost() && ++n < 60) tick() }, 120)
      return
    }
    // Skærmene indlæses først, når de vises: vent op til 3 sekunder på overskriften
    if (++n < 60) { tm = setTimeout(tick, 50); return }
    const m = document.getElementById('main')
    if (m) CW.focusSoon(m)
  }
  tick()
}, { flush: 'post' })

// "Spring til indhold": flyt fokus til hovedindholdet uden at røre URL'en
function skipToMain () {
  const m = document.getElementById('main')
  if (m) m.focus()
}

// Navigationspanelet på smalle skærme, som før migrationen (app.jsx): en modal dialog med navnet
// Hovedmenu. Når det åbner, får det aktive menupunkt fokus, og Tab bliver i panelet. Esc og
// lukkeknappen (Luk menuen) lukker og giver fokus tilbage til menuknappen. Et klik på baggrunden, et
// sideskift, et klik på en knap i panelet eller fokus, der forlader panelet (fx når en dialog åbner
// fra "Ny sag"), lukker det uden at flytte fokus.
let refocusToggle = false
function closeNavPanel (focusToggle) {
  refocusToggle = !!focusToggle
  closeNav()
}
function onDrawerClose (e) {
  // antdv melder close for Esc (tastatur) og for et klik på baggrunden
  closeNavPanel(!!e && e.type === 'keydown')
}
const navTrap = useFocusTrap()
watch(navOpen, (open) => {
  if (open) navTrap.trap(() => document.getElementById('cw-nav-panel'))
  else navTrap.release()
})
function afterNavChange (open) {
  if (open) {
    const panel = document.getElementById('cw-nav-panel')
    const first = panel && (panel.querySelector('[aria-current="page"]') || panel.querySelector('nav li[role="button"], button'))
    if (first) CW.focusSoon(first)
    return
  }
  if (refocusToggle) CW.focusSoon('#cw-nav-toggle')
  refocusToggle = false
}
function onNavFocusOut (e) {
  if (!navOpen.value) return
  const to = e.relatedTarget
  // Brugermenuen åbner uden for panelet (antdv lægger den i body), men hører til det
  if (to && (to.closest('.cw-nav-drawer') || to.id === 'cw-nav-toggle' || to.closest('#cw-user-menu'))) return
  closeNavPanel(false)
}
function onNavClick (e) {
  const el = e.target
  if (!el.closest || !el.closest('button')) return
  if (el.closest('[role="group"], [role="radiogroup"], [aria-haspopup], [role="menu"]')) return
  closeNavPanel(false)
}
</script>

<template>
  <a-config-provider :locale="antdLocale">
    <!-- Kundens portal: egen skærm uden sidebjælke; tilbage fører til sag 1 -->
    <CustomerPortalView
      v-if="route === 'portal'"
      @back="go('workspace:1')"
    />
    <template v-else>
      <a
        href="#main"
        class="skip-link"
        @click.prevent="skipToMain"
      >{{ t('Spring til indhold') }}</a>
      <a-layout class="app">
        <a-layout-sider
          v-if="!narrow"
          theme="light"
          :width="229"
          class="app-sider"
        >
          <AppSidebar />
        </a-layout-sider>
        <a-drawer
          v-else
          :visible="navOpen"
          class="cw-nav-drawer"
          placement="left"
          :width="229"
          :closable="false"
          :body-style="{ padding: 0, overflowX: 'hidden' }"
          destroy-on-close
          @close="onDrawerClose"
          @after-visible-change="afterNavChange"
        >
          <!-- Som sidebjælken på brede skærme ruller panelet kun lodret (menuens punkter er 1 px bredere end menuen).
               Dialogen er panelets indhold: a-drawer i 3.2.13 sender hverken role eller aria-* videre, og
               dens egen lukkeknap hedder altid "Close". Lukkeknappen står, hvor menuknappen stod, som før. -->
          <div
            id="cw-nav-panel"
            role="dialog"
            aria-modal="true"
            :aria-label="t('Hovedmenu')"
            @focusout="onNavFocusOut"
            @click="onNavClick"
          >
            <div class="nav-panel-head">
              <a-button
                type="text"
                :aria-label="t('Luk menuen')"
                :title="t('Luk menuen')"
                @click.stop="closeNavPanel(true)"
              >
                <template #icon>
                  <CloseOutlined aria-hidden="true" />
                </template>
              </a-button>
            </div>
            <AppSidebar />
          </div>
        </a-drawer>
        <a-layout class="app-main">
          <main
            id="main"
            tabindex="-1"
          >
            <PortfolioView v-if="route === 'cases'" />
            <WorkspaceView
              v-if="isWorkspace"
              :case-id="workspaceCaseId"
              :tab="workspaceTab"
            />
            <PortfolioAnalyseView v-if="route === 'analyse'" />
            <DataRequestsView v-if="route === 'requests'" />
            <!-- Demo: kontomappingen -->
            <MapperView v-if="route === 'mapping'" />
            <!-- Internt: Prompt-værkstedet -->
            <PromptWorkshopView v-if="route === 'prompts'" />
          </main>
        </a-layout>
      </a-layout>
    </template>

    <!-- Ny sag: fra knappen og fra andre skærme ('cw-new-case') -->
    <NewCaseHost />
    <TweaksPanel />
    <ConfirmDialog />
  </a-config-provider>
</template>

<style scoped lang="less">
@import (reference) 'ant-design-vue/lib/style/themes/default.less';

.app {
  min-height: 100vh;
}

/* Sidebjælken står stille, mens indholdet ruller, og har sin egen lodrette rulning */
.app-sider {
  position: sticky;
  top: 0;
  height: 100vh;
  overflow-x: hidden;
  overflow-y: auto;
  border-right: 1px solid @border-color-split;
}

main:focus {
  outline: none;
}

/* Lukkeknappen i navigationspanelet, på linje med sidebjælkens indhold */
.nav-panel-head {
  padding: 12px 16px 0;
}
</style>
